# Generated by Django 4.2.21 on 2025-12-22 17:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10)),
                ('version', models.CharField(max_length=20)),
                ('minimum_supported_version', models.CharField(max_length=20)),
                ('update_type', models.CharField(choices=[('optional', 'Optional'), ('force', 'Force')], default='optional', max_length=10)),
                ('apk_file', models.FileField(help_text='Upload the APK file for Android platform.', upload_to='apk_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['apk'])])),
                ('is_active', models.BooleanField(default=True)),
                ('user_created', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('platform', 'version')},
            },
        ),
    ]
