# Generated by Django 4.2.21 on 2025-12-26 13:03

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('version', models.CharField(max_length=20, unique=True)),
                ('minimum_supported_version', models.CharField(max_length=20)),
                ('apk_file', models.FileField(help_text='Upload the APK file for Android platform.', upload_to='apk_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['apk'])])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
