# Generated by Django 4.2.21 on 2025-12-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appversion', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appversion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='version',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.RemoveField(
            model_name='appversion',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='appversion',
            name='update_type',
        ),
    ]
