# Generated by Django 4.2.21 on 2025-12-27 14:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appversion', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppVersion',
            new_name='AndroidAppRelease',
        ),
    ]
