# Generated by Django 4.2.21 on 2026-01-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0002_employeeovertime_delete_overtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeovertime',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
