# Generated by Django 4.2.21 on 2025-06-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_fcm_token_user_preferred_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('artisan', 'Artisan'), ('client', 'Client')], max_length=20),
        ),
    ]
