# Generated by Django 4.2.21 on 2025-10-24 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_language',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
