# Generated by Django 4.2.21 on 2025-12-26 13:03

import apps.core.mixins
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_online', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(apps.core.mixins.SoftDeleteUniqueMixin, models.Model),
        ),
    ]
