# Generated by Django 4.2.21 on 2025-12-27 14:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLocation',
            new_name='EmployLocation',
        ),
    ]
