# Generated by Django 4.2.21 on 2025-10-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_userlocation_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
