# Generated by Django 4.2.21 on 2025-12-12 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_userlocation_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
