# Generated by Django 4.2.21 on 2025-12-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='checkout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
