# Generated by Django 4.2.21 on 2025-12-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_overtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
